version: '3'
services:
 
  mysql:
    image: mysql:8.0
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: app_db
    env_file:
      - .env
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
 
 
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./src/uploads:/var/www/html/uploads:rw
    restart: on-failure
    links:
      - "mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      UPLOAD_DIR: uploads/icons/
    depends_on:
      - mysql

 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    links:
      - "mysql"
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  dbdata:
  uploads:
