version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: app_db
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    links:
      - "mysql"
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  app:
    image: php:8-apache
    restart: on-failure
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=app_db
      - MYSQL_HOST=mysql
    depends_on:
      - mysql

volumes:
  dbdata:
  uploads:
